## Q1)


In [2]:
from statistics import median


def sum(arr,m):
    n=len(arr)
    count=0
    for i in range(n):
        for j in range(i+1,n):
            if arr[i]+arr[j]==m:
                count+=1
    return count
a=[2,7,4,1,3,6]
m=10
result=sum(a,m)
print(result)

2


## Q2)


In [9]:
a=list(map(int,input("enter the elements of the list").split()))
if len(a)<3:
    print("rnage determination is not possible")
else:
    range=[max(a),min(a)]
    print("range is ",range)


rnage determination is not possible


## Q3)

In [10]:
import numpy as np
a = np.array([[2, 7, 4],[3, 8, 5],[4, 9, 6]])
m=int(input("enter the value of the power"))
result = np.linalg.matrix_power(a, m)
print(result)

[[178952 465532 293584]
 [219116 570016 359476]
 [259280 674500 425368]]


## Q4)

In [23]:
s="Hippopotamus"
a=max(s,key=s.count)
print(f"the most repeated is {a} count is {s.count(a)}")

the most repeated is g count is 2


## Q5)

In [23]:
import random,numpy
arr=[]
for _ in range(25):
    arr.append(random.randint(1,10))
mean=numpy.mean(arr)
median=numpy.median(arr)
mode=max(arr,key=arr.count)
print(f"mean is {mean},median is {median},mode is {mode}")

 mean is 6.12,median is 7.0,mode is 10


In [3]:
s="hello world"
print(s[1])

e
